# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. Please do not edit it directly.
class DeltaCli < Formula
  desc "Offline AI Assistant powered by llama.cpp"
  homepage "https://github.com/nile-agi/delta"
  license "MIT"
  # Use head version for now (release version will be added when v1.0.0 is tagged)
  # Note: submodules handled manually in install method to avoid nested repo issues
  head "https://github.com/nile-agi/delta.git", branch: "main"
  
  # Release version (uncomment when v1.0.0 is released)
  # url "https://github.com/nile-agi/delta/archive/refs/tags/v1.0.0.tar.gz"
  # sha256 "PLACEHOLDER_SHA256"
  # version "1.0.0"

  depends_on "cmake" => :build
  depends_on "curl" => :build
  depends_on "pkg-config" => :build

  on_macos do
    depends_on :macos
  end

  on_linux do
    depends_on "gcc" => :build
  end

  def install
    # Initialize and update only the llama.cpp submodule
    # This avoids issues with nested repos like homebrew-delta-cli
    system "git", "submodule", "update", "--init", "vendor/llama.cpp"
    
    # Update llama.cpp's submodules if it has any
    if Dir.exist?("vendor/llama.cpp/.gitmodules")
      cd "vendor/llama.cpp" do
        system "git", "submodule", "update", "--init", "--recursive"
      end
    end
    
    # Create build directory
    mkdir "build" do
      system "cmake", "..",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DGGML_METAL=#{OS.mac? ? "ON" : "OFF"}",
                    "-DLLAMA_CUDA=OFF",
                    "-DLLAMA_VULKAN=OFF",
                    "-DLLAMA_HIPBLAS=OFF",
                    "-DBUILD_SERVER=ON",
                    "-DUSE_CURL=ON",
                    *std_cmake_args
      system "make", "-j#{ENV.make_jobs}"
    end

    # Install binaries
    bin.install "build/delta"
    bin.install "build/delta-server"

    # Install web UI
    if Dir.exist?("vendor/llama.cpp/tools/server/public")
      share.install "vendor/llama.cpp/tools/server/public" => "delta-cli/webui"
    end
  end

  test do
    system "#{bin}/delta", "--version"
  end
end

